spring:
  kafka:
    consumer:
      group-id: test
      auto-offset-reset: earliest
      bootstrap-servers: http://192.168.3.189:9092
    producer:
      client-id: produceTest
      bootstrap-servers: http://192.168.3.189:9092