dubbo:
  application:
    name: simple-producer
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 20880
  provider:
    token: true
logging:
  level:
    root: warn
    org.example.producer: debug
