FROM golang:1.17-alpine as builder
WORKDIR /usr/src/app
ARG PROFILE=dc
ENV GOPROXY=https://goproxy.cn
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories && \
  apk add --no-cache upx ca-certificates tzdata protobuf-dev
COPY ../go.mod ./
COPY ../go.sum ./
RUN go mod download
COPY .. .

RUN  go get -u github.com/golang/protobuf/protoc-gen-go &&\
  	 go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc &&\
     go generate &&\
     CGO_ENABLED=0 go build -ldflags "-s -w" -o server cmd/server.go

FROM scratch as runner
ARG PROFILE=dc
COPY --from=builder /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/src/app/server /opt/app/
COPY --from=builder /usr/src/app/conf/dubbogo-${PROFILE}.yaml /opt/app/dubbogo.yaml

ENV DUBBO_GO_CONFIG_PATH=/opt/app/dubbogo.yaml
CMD ["/opt/app/server"]
