version: "2"
services:
  nacos:
    image: nacos/nacos-server:2.0.3
    env_file:
      - ./nacos-standlone-mysql.env
    volumes:
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always
  mysql:
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ./mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  go-producer:
    image: go-producer:0.1-dc
  java-producer:
    image: producer-simple:1.0-SNAPSHOT
    environment:
      spring_profiles_active: dc
  java-consmuer:
    image: consumer-simple:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      spring_profiles_active: dc

