spring:
  application:
    name: simple-consumer
  output:
    ansi:
      enabled: ALWAYS
  main:
    banner-mode: off

nacos:
  host: nacos-cs
  port: 8848
  username: nacos
  password: nacos

dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
logging:
  level:
    root: warn
    org:
      example:
        producer: debug
        comsumer: debug
